### ISSUE TITLE
'mask1_model_resnet50.pth' not Found

### ISSUE THREAD

**Issue by hanouel** [prajnasb/observations#3]
Hello,
Thank you for sharing your code. I try to execute it but this error is appeared `FileNotFoundError: [Errno 2] No such file or directory: 'mask1_model_resnet50.pth'` 
Can you please share this file? 
Thank you

**Comment by mherrera-dsci** [comment]
Hello @hanouel, you must train with the jupyter notebook for get the file mask1_model_resnet**101**.pth, then you must be modify the file label_detect.py in line 27
filepath = 'mask1_model_resnet**101**.pth'
Regards,

**Comment by aniquazereen** [comment]
Can you please upload the model file?

**Comment by ReStark01** [comment]
I've trained with the jupyter notebook and i get the file mask1_model_resnet101.pth,
I've do
filepath = 'mask1_model_resnet101.pth'
But torch.load method can't open zip file. So i've do torch.jit.load but get issues again.
Need some help please.
Best regards
